\#  For more details on the layout of this page and how to process it
\#  to create PDF and HTML, see the comment header for bfast.1
\#
\#
\# .TP
\# \fB\-I\fR, \fB\-\-ignore\fR=\fIPATTERN\fR
\# do not list implied entries matching shell PATTERN
\#
\" Turn off justification and hyphenation
.na
.hy 0
.TH bpostprocess 1 "UCLA bfast"
.SH NAME
bpostprocess \- converts alignment files to the user-specified format.
.SH SYNOPSIS
.P
.fam C
.nf
bpostprocess
	[\fB\-r\fR \fIFILENAME\fR]	[\fB\-\-rgFileName=\fIFILENAME\fR]
	[\fB\-i\fR \fIFILENAME\fR] 	[\fB\-\-alignFileName=\fIFILENAME\fR]
	[\fB\-2\fR]			[\fB\-\-pairedEnd\fR]
	[\fB\-a\fR \fIINTEGER\fR]	[\fB\-\-algorithmReads=\fIINTEGER\fR]
	[\fB\-A\fR \fIINTEGER\fR]	[\fB\-\-algorithmReadsPaired=\fIINTEGER\fR]
	[\fB\-C\fR]			[\fB\-\-contigAbPaired\fR]
	[\fB\-I\fR]			[\fB\-\-inversionsPaired\fR]
	[\fB\-s\fR \fIINTEGER\fR] 	[\fB\-\-startContig=\fIINTEGER\fR]
	[\fB\-S\fR \fIINTEGER\fR] 	[\fB\-\-startPos=\fIINTEGER\fR]
	[\fB\-e\fR \fIINTEGER\fR] 	[\fB\-\-endContig=\fIINTEGER\fR]
	[\fB\-E\fR \fIINTEGER\fR] 	[\fB\-\-endPos=\fIINTEGER\fR]
	[\fB\-m\fR \fIINTEGER\fR] 	[\fB\-\-minScoreReads=\fIINTEGER\fR]
	[\fB\-j\fR \fIINTEGER\fR]	[\fB\-\-maxMismatches=\fIINTEGER\fR]
	[\fB\-k\fR \fIINTEGER\fR]	[\fB\-\-maxColorErrors=\fIINTEGER\fR]
	[\fB\-M\fR \fIINTEGER\fR] 	[\fB\-\-minScoreReadsPaired=\fIINTEGER\fR]
	[\fB\-X\fR \fIINTEGER\fR]	[\fB\-\-minDistancePaired=\fIINTEGER\fR]
	[\fB\-Y\fR \fIINTEGER\fR]	[\fB\-\-maxDistancePaired=\fIINTEGER\fR]
	[\fB\-J\fR \fIINTEGER\fR]	[\fB\-\-maxMismatchesPaired=\fIINTEGER\fR]
	[\fB\-K\fR \fIINTEGER\fR]	[\fB\-\-maxColorErrorsPaired=\fIINTEGER\fR]
	[\fB\-o\fR \fISTRING\fR] 	[\fB\-\-outputID=\fISTRING\fR]
	[\fB\-d\fR \fIDIRECTORY\fR] [\fB\-\-outputDir=\fIDIRECTORY\fR]
	[\fB\-O\fR \fIINTEGER\fR] 	[\fB\-\-outputFormat=\fIINTEGER\fR]
	[\fB\-t\fR] 		[\fB\-\-timing\fR]
	[\fB\-p\fR] 		[\fB\-\-Parameters\fR]
	[\fB\-h\fR] 		[\fB\-\-Help\fR]
.fi
.fam
.
.SH KNOWN ISSUES
Please see the
.BR bfast (1) 
manpage.
.
.SH AUTHORS
.P
Nils Homer <nhomer@cs.ucla.edu.org>
.br
Barry Merriman <barrym@ucla.edu>
.br
Stanley F. Nelson <snelson@ucla.edu>
.
.SH SEE ALSO
.P
.BR bfast "(1), "
.BR bpreprocess "(1), "
.BR bmatches "(1), "
.BR balign "(1),"
.BR butil "(1)."
.
.SH COPYRIGHT
.P
bfast is copyright 2008 by The University of California - Los
Angeles.  All rights reserved.  This License is limited to, and you
may use the Software solely for, your own internal and non-commercial
use for academic and research purposes.  Without limiting the foregoing,
you may not use the Software as part of, or in any way in connection
with the production, marketing, sale or support of any commercial
product or service.  For commercial use, please contact
snelson@ucla.edu.  By installing this Software you are agreeing to
the terms of the LICENSE file distributed with this software.
.
.P
In any work or product derived from the use of this Software, proper
attribution of the authors as the source of the software or data must
be made.  Please reference the original BFAST paper PMID<to be published>.
In addition, the following URL should be cited:
.
.P
.I <http://genome.ucla.edu/bfast>
