\#  For more details on the layout of this page and how to process it
\#  to create PDF and HTML, see the comment header for bfast.1
\#
\#
\# .TP
\# \fB\-I\fR, \fB\-\-ignore\fR=\fIPATTERN\fR
\# do not list implied entries matching shell PATTERN
\#
\" Turn off justification and hyphenation
.na
.hy 0
.TH butil 1 "UCLA bfast"
.SH NAME
butil \- utilities for bfast (not supported)
.SH SYNOPSIS
.P
.fam C
.nf
.
bafconvert [OPTIONS]
	<bfast aligned file name>
	<input type: 0-text 1-binary>

bevalsim [OPTIONS]
	<bfast aligned file>
	<output id>

bexonify [OPTIONS]
	<bfast reference genome file>
	<bfast index file>
	<exon list file>

bfixhash [OPTIONS]
	<bfast reference genome file>
	<bfast index file>
	<new hash width>

bgeneratereads [OPTIONS]
	<bfast reference genome file name (must be in nt space)>
	<space 0: nt space 1: color space>
	<indel 0: none 1: deletion 2: insertion>
	<indel length>
	<include errors within insertion 0: false 1: true>
	<# of SNPs>
	<# of errors>
	<read length>
	<paired end 0: false 1: true>
	<paired end length>
	<number of reads>

bheader [OPTIONS]
	<input file>

bindexdist [OPTIONS]
	<bfast reference genome file>
	<bfast index file name>
	<number of mismatches>
	<output directory>
	<output id>
	<tmp file directory>
	<number of threads>

bindexhist [OPTIONS]
	<bfast reference genome file name>
	<bfast index file name>
	<number of mismatches for histogram>
	<number of threads>

bmfconvert [OPTIONS]
	<bfast matches file name>
	<input type: 0-text 1-binary>
	<0-single-end 1-paired end>

bpairedenddist [OPTIONS]
	<bfast matches file name>
	<binary Input: 0-text 1-binary>

brepeat [OPTIONS]
	<bfast reference genome file>
	<minimum unit length>
	<maximum unit length>
	<minimum total repeat length>

breport [OPTIONS]
	<bfast baf file name>
	<maximum number of entries when sorting>
	<tmp file directory

btestindexes [OPTIONS]
******************************* Algorithm Options (no defaults) *******************************
	-a	INT	algorithm
	0: search for indexes
	1: evaluate indexes
	-r	INT	read length (for all) 
	-S	INT	number of events to sample
	-A	INT	space 0: nucleotide space 1: color space
******************************* Search Options (for -a 0) *************************************
	-s	INT	number of indexes to sample
	-l	INT	key size
	-w	INT	maximum key width
	-n	INT	maximum index set size
	-t	INT	accuracy percent threshold (0-100)
******************************* Evaluate Options (for -a 1) ***********************************
	-f	STRING	input file name
	-I	INT	maximum insertion length (-a 1)
******************************* Event Options (default =0 ) ***********************************
	-M	INT	maximum number of mismatches
	-E	INT	maximum number of color errors (-A 1)
******************************* Miscellaneous Options  ****************************************
	-p	NULL	prints the program parameters
	-h	NULL	prints this message
.fi
.fam
.
.SH DESCRIPTION
.B butil 
is a folder containing utilities that were developed for personal use to test, debug, and compliment the bfast program and its accompanying publication.
They are included in this distribution to aid in using bfast and to give examples of other uses for the indexes built and data generated by bfast.
There is no support or warranty for these utilities.
If options are not specified in the correct order, data may be overwritten, and crashes will certainly occur.
Please use at your own risk and consult the source code if problems arise.
If you find one of these utilities incredibly useful, please contact the authors/developers as to recommend a utility be supported.
.
.SH KNOWN ISSUES
Please see the
.BR bfast (1) 
manpage.
.
.SH AUTHORS
.P
Nils Homer <nhomer@cs.ucla.edu.org>
.br
Barry Merriman <barrym@ucla.edu>
.br
Stanley F. Nelson <snelson@ucla.edu>
.
.SH SEE ALSO
.P
.BR bfast "(1), "
.BR bpreprocess "(1), "
.BR bmatches "(1), "
.BR balign "(1), "
.BR bpostprocess "(1)."
.
.SH COPYRIGHT
.P
bfast is copyright 2008 by The University of California - Los
Angeles.  All rights reserved.  This License is limited to, and you
may use the Software solely for, your own internal and non-commercial
use for academic and research purposes.  Without limiting the foregoing,
you may not use the Software as part of, or in any way in connection
with the production, marketing, sale or support of any commercial
product or service.  For commercial use, please contact
snelson@ucla.edu.  By installing this Software you are agreeing to
the terms of the LICENSE file distributed with this software.
.
.P
In any work or product derived from the use of this Software, proper
attribution of the authors as the source of the software or data must
be made.  Please reference the original BFAST paper PMID<to be published>.
In addition, the following URL should be cited:
.
.P
.I <http://genome.ucla.edu/bfast>
